adding greg service script

diff --git a/wso2greg/templates/4.6.0/wso2greg.erb b/wso2greg/templates/4.6.0/wso2greg.erb
--- a/wso2greg/templates/4.6.0/wso2greg.erb
+++ b/wso2greg/templates/4.6.0/wso2greg.erb
@@ -1,153 +1,158 @@
 #!/bin/bash
 #
-# chkconfig: 35 90 12
-#
+# /etc/init.d/as
+# chkconfig:         2345 90 10
+# description:       wso2 service init script.
+# Provides:          wso2 Inc
+# Required-Start:    $syslog 
+# Should-Start:
+# Required-Stop:     $syslog 
+# Should-Stop:
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
+# Short-Description:  wso2as # 
 # Get function from functions library
-. /etc/init.d/functions
+if [ -f /etc/init.d/functions ]; then
+      . /etc/init.d/functions
+  else
+      . /lib/lsb/init-functions
+fi 
 
+
+#set the configuration settings for the service
 USER="<%= @owner %>"
-PRODUCT_CODE="<%= @deployment_code %>"
+PRODUCT_CODE="Goverance Registry"
 CARBON_HOME="<%= @carbon_home %>"
 LOCK_FILE="${CARBON_HOME}/wso2carbon.lck"
 PID_FILE="${CARBON_HOME}/wso2carbon.pid"
 CMD="${CARBON_HOME}/bin/wso2server.sh"
 
-# Status the service
+#Get the status details of idenetity service
 status() {
-	if [ -f $PID_FILE ]
-	    then
-		PID=`cat $PID_FILE`
-		ps -fp $PID > /dev/null 2>&1
-		PIDVAL=$?
-	    else
-		PIDVAL=3
-	fi
+     if [ -f $PID_FILE ]; then
+        PID=`cat $PID_FILE`
+        ps -fp $PID > /dev/null 2>&1
+        PIDVAL=$?
+     else
+        PIDVAL=3
+     fi
 
-	if [ $PIDVAL -eq 0 ]
-	    then
-		echo "WSO2 $PRODUCT_CODE server is running ..."
-	    else
-		echo "WSO2 $PRODUCT_CODE server is stopped."
-	fi
-	return $PIDVAL
+     if [ $PIDVAL -eq 0 ]; then
+        echo "WSO2 $PRODUCT_CODE server is running ..."
+     else
+        echo "WSO2 $PRODUCT_CODE server is stopped."
+     fi
+     echo
+     return $PIDVAL
 }
 
-# Start the service
+#Start the idenetity service
 start() {
-	if [ -f $PID_FILE ]
-	    then
-		PID=`cat $PID_FILE`
-		ps -fp $PID > /dev/null 2>&1
-		PIDVAL=$?
-	    else
-		PIDVAL=3
-	fi
+     if [ -f $PID_FILE ]; then
+        PID=`cat $PID_FILE`
+        ps -fp $PID > /dev/null 2>&1
+        PIDVAL=$?
+     else
+        PIDVAL=3
+     fi
 
-	if [ $PIDVAL -eq 0 ]
-	    then
-	       echo "WSO2 $PRODUCT_CODE server is running ..."
-	    else
-	       echo -n "Starting WSO2 $PRODUCT_CODE server: " 
-	       touch $LOCK_FILE
-	       su - $USER -c "$CMD start > /dev/null 2>&1 &"
-	       sleep 5
-	       if [ -f $PID_FILE ]
-		   then
-			PID=`cat $PID_FILE`
-			ps -fp $PID > /dev/null 2>&1
-			PIDVAL=$?
-			if [ $PIDVAL -eq 0 ]
-			    then
-				success $
-			    else
-				failure $
-			fi
-		   else
-			failure $
-			PIDVAL=2
-	       fi
-	fi
-	echo
-	return $PIDVAL
+     if [ $PIDVAL -eq 0 ]; then
+        echo "WSO2 $PRODUCT_CODE server is running ..."
+     else
+        echo -n "Starting WSO2 $PRODUCT_CODE server: "
+        touch $LOCK_FILE
+        su - $USER -c "$CMD start > /dev/null 2>&1 &"
+        sleep 5
+        if [ -f $PID_FILE ]; then
+            PID=`cat $PID_FILE`
+            ps -fp $PID > /dev/null 2>&1
+            PIDVAL=$?
+            if [ $PIDVAL -eq 0 ]; then
+                echo "[Ok]"
+            else
+                echo "[Fail]"
+            fi
+        else
+            echo "[Fail]"
+            PIDVAL=2
+        fi
+     fi
+     echo
+     return $PIDVAL
 }
 
-# Restart the service
+#Restart the idenetity service
 restart() {
-	echo -n "Restarting WSO2 $PRODUCT_CODE server: " 
-	touch $LOCK_FILE
-	su - $USER -c "$CMD restart > /dev/null 2>&1 &"
-	sleep 15
-	if [ -f $PID_FILE ]
-	    then
-		PID=`cat $PID_FILE`
-		ps -fp $PID > /dev/null 2>&1
-		PIDVAL=$?
-		if [ $PIDVAL -eq 0 ]
-		    then
-			success $
-		    else
-			failure $
-		fi
-	    else
-		failure $
-		PIDVAL=2
-	fi
-	echo
-	return $PIDVAL
+    echo -n "Restarting WSO2 $PRODUCT_CODE server: "
+    touch $LOCK_FILE
+    su - $USER -c "$CMD restart > /dev/null 2>&1 &"
+    sleep 15
+    if [ -f $PID_FILE ]; then
+        PID=`cat $PID_FILE`
+        ps -fp $PID > /dev/null 2>&1
+        PIDVAL=$?
+        if [ $PIDVAL -eq 0 ]; then
+            echo "[Ok]" 
+        else
+            echo "[Fail]"
+        fi
+    else
+        echo "[Fail]"
+        PIDVAL=2
+    fi
+    echo
+    return $PIDVAL
 }
 
-# Stop the service
+#Stop the idenetity service
 stop() {
-	if [ -f $PID_FILE ]
-	    then
-		PID=`cat $PID_FILE`
-		ps -fp $PID > /dev/null 2>&1
-		PIDVAL=$?
-		if [ $PIDVAL -eq 0 ]
-		    then
-			echo -n "Stopping WSO2 $PRODUCT_CODE server: "
-			su - $USER -c "$CMD stop > /dev/null 2>&1 &"
-			rm -f $LOCK_FILE 
-			sleep 10
-			PID=`cat $PID_FILE`
-			ps -fp $PID > /dev/null 2>&1
-			PIDVAL=$?
-			if [ $PIDVAL -eq 0 ]
-			    then
-				failure $
-				PIDVAL=2
-			    else
-				success $
-				PIDVAL=0
-			fi
-		    else
-		       echo "WSO2 $PRODUCT_CODE server is not running."
-		       PIDVAL=0
-		fi
-	    else
-	       echo "WSO2 $PRODUCT_CODE server is not running."
-	       PIDVAL=0
-	fi
-	echo
-	return $PIDVAL
+    if [ -f $PID_FILE ]; then
+        PID=`cat $PID_FILE`
+        ps -fp $PID > /dev/null 2>&1
+        PIDVAL=$?
+        if [ $PIDVAL -eq 0 ]; then
+            echo -n "Stopping WSO2 $PRODUCT_CODE server: "
+            su - $USER -c "$CMD stop > /dev/null 2>&1 &"
+            rm -f $LOCK_FILE
+            sleep 10
+            PID=`cat $PID_FILE`
+            ps -fp $PID > /dev/null 2>&1
+            PIDVAL=$?
+            if [ $PIDVAL -eq 0 ]; then
+                echo "[Fail]"
+                PIDVAL=2
+            else
+                echo "[Ok]"
+                PIDVAL=0
+            fi
+         else
+            echo "WSO2 $PRODUCT_CODE server is not running."
+            PIDVAL=0
+         fi
+    else
+         echo "WSO2 $PRODUCT_CODE server is not running."
+         PIDVAL=0
+    fi
+    echo
+    return $PIDVAL
 }
 
-### main logic ###
+###Main logic of the service###
 case "$1" in
 start)
-    start
-    ;;
+  start
+  ;;
 stop)
-    stop
-    ;;
+  stop
+  ;;
 status)
-    status
-    ;;
+  status
+  ;;
 restart|reload|condrestart)
-    restart
-    ;;
+  restart
+  ;;
 *)
-   echo $"Usage: $0 {start|stop|restart|reload|status}"
-   exit 1
+  echo  $"Usage: $0 {start|stop|restart|reload|status}"
+  exit 1
 esac
 exit $?
